[package]
name = "sieri-xf"
version = "0.1.0"
edition = "2021"
description = "An event driven multiplateform execution framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
